<?php 
include_once(dirname(dirname(__FILE__)).'/config/config.php');

include_once('super.php');
include_once('class_secret.php');    
include_once('check_login.php');

?>
<!DOCTYPE html>
<html Class="lockscreen">
    <head>
        <meta charset="ISO 8859-1">
        <title><?php echo (NOME_PRJ); ?> | Lockscreen</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        
        <?php include_once(THEME.'/include/lib_js.php'); ?>	

    </head>
    <body>
        <!-- Automatic element centering using js -->
        <div Class="center">            
			<div Class="headline text-center" id="date"></div>
            <div Class="headline text-center" id="time">
                <!-- Time auto generated by js -->
            </div><!-- /.headline -->
            
            <!-- User name -->
            <!-- <div Class="lockscreen-name"><?php echo ( (isset($Dashboard_user->nickname) ? $Dashboard_user->nickname : $Dashboard_user->username ) ); ?></div> -->
            
			<form role="form" method="post">
            <!-- START LOCK SCREEN ITEM -->
            <div Class="lockscreen-item">
                <!-- lockscreen image -->
                <div Class="lockscreen-image">
                    <img src="img/avatar5.png" alt="user image"/>
                </div>
                <!-- /.lockscreen-image -->

                <!-- lockscreen credentials (contains the form) <input type="hidden" name="utente" value="<?php //echo ($_SESSION['user']); ?>"/>-->
						
					<div Class="lockscreen-credentials">   
						<div Class="input-group <?php echo ( (sizeof($errors) > 0) ? 'has-error' : '' ); ?>">
							<?php if(sizeof($errors) > 0) { ?>
								<label Class="control-label" for="inputError"><i Class="fa fa-times-circle-o"></i> Input with error</label>
							<?php } ?>
							<input type="text" Class="form-control" name="utente" placeholder="User ID" />
						</div>
						<div Class="input-group <?php echo ( (sizeof($errors) > 0) ? 'has-error' : '' ); ?>">
							<?php if(sizeof($errors) > 0) { ?>
								<label Class="control-label" for="inputError"><i Class="fa fa-times-circle-o"></i> Input with error</label>
							<?php } ?>
							<input type="password" Class="form-control" name="password" placeholder="password" />
							<div Class="input-group-btn">
								<button Class="btn btn-flat"><i Class="fa fa-arrow-right text-muted"></i></button>
							</div>
						</div>
					</div><!-- /.lockscreen credentials -->
            </div><!-- /.lockscreen-item -->
				</form>

            <div Class="lockscreen-link">
                <a href="login.php">Or sign in as a different user</a>
            </div>            
        </div><!-- /.center -->

        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="js/bootstrap.min.js" type="text/javascript"></script>

        <!-- page script -->
        <script type="text/javascript">
            $(function() {
                startTime();
                $(".center").center();
                $(window).resize(function() {
                    $(".center").center();
                });
            });

            /*  */
            function startTime()
            {
                var today = new Date();
                var h = today.getHours();
                var m = today.getMinutes();
                var s = today.getSeconds();

				var month = today.getMonth()+1;
				var day = today.getDate();

				var output = (day<10 ? '0' : '') + day + '/' + (month<10 ? '0' : '') + month + '/' + today.getFullYear();
	
                // add a zero in front of numbers<10
                m = checkTime(m);
                s = checkTime(s);

                //Check for PM and AM
                var day_or_night = (h > 11) ? "PM" : "AM";

                //Convert to 12 hours system
                /*if (h > 12)
                    h -= 12;*/

                //Add time to the headline and update every 500 milliseconds
                $('#time').html(h + ":" + m + ":" + s + " " );
                setTimeout(function() {
                    startTime()
                }, 500);
				
				$('#date').html(output);
            }

            function checkTime(i)
            {
                if (i < 10)
                {
                    i = "0" + i;
                }
                return i;
            }

            /* CENTER ELEMENTS IN THE SCREEN */
            jQuery.fn.center = function() {
                this.css("position", "absolute");
                this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
                        $(window).scrollTop()) - 30 + "px");
                this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
                        $(window).scrollLeft()) + "px");
                return this;
            }
        </script>
    </body>
</html>
<?php include_once('footer.php')?>