
var template = 
{
    "AVATARS"	:  	'<div class="box-txt-edit-photo"> 	<div class="img-profilo-modifica" > <div id="MKUID">		<div class="upload-drop-zone" id="MKUID_drop-zone" style="height: 103px; width: 119px; padding-top: 32px;"> 			<div class="hover-cambia-immagine"></div>			 			<img src="images/maschera-esagono-gray.png" class="maschera-esagono" alt="" id="MKUID_upload_btn"/> 			<img id="MKUID_img_src" width="100%" alt=""/> 			<input type="file" name="files[]" id="MKUID_avatar" style="display:none;" /> 			<input type="text" name="avatar" id="MKUID_text-avatar"	class="form-control" value="" style="display:none;"/> 	</div>	</div> 	</div> </div>',
	"IMG"	:  	'<div class="col-sm-3"><div class="form-group"><div class="field" id="MKUID"><div class="upload-drop-zone" id="MKUID_drop-zone" style="height: 230px; width: 230px;line-height: 40px;"><img id="MKUID_img_src" class="thumbnail img-responsive" style="min-height: 225px; min-width: 225px;" /></div><br /><div class="input-group input-group-sm"><input type="file" name="files[]" id="MKUID_avatar" style="display:none;" /><input type="text" name="avatar" id="MKUID_text-avatar"	class="form-control"	value="" /><span class="input-group-btn"><button class="btn btn-info btn-flat" type="button" id="MKUID_upload_btn" >Carica</button></span></div></div></div></div>',
	"FULL"	:	'<button name="upload_btn_MKUID" class="btn btn-info" type="button" id="upload_btn_MKUID">Apri Caricamento</button><p><img src="" id="img-MKUID-src" onClick="openImg(this.src);"/></p><input type="text" name="img_MKUID" id="img_MKUID" class="form-control" readonly placeholder="Nessun file caricato" onChange="ChangeForm();" value="">',
	"DND"	:	'<div class="panel panel-default"><div class="panel-heading"><strong>Upload Files</strong> <small>Bootstrap files upload</small></div><div class="panel-body" id="MKUID">   <!-- Standar Form -->  <h4>Select files from your computer</h4>  <form action="" method="post" enctype="multipart/form-data" id="MKUID_js-upload-form" class="js-upload-form">    <div class="form-inline">      <div class="form-group">        <input type="file" name="files[]" id="js-upload-files" multiple>      </div>      <button type="submit" class="btn btn-sm btn-primary" id="js-upload-submit">Upload files</button>    </div>     <!-- Drop Zone -->  <h4>Or drag and drop files below</h4>  <div class="upload-drop-zone" id="MKUID_drop-zone">    Just drag and drop files here  </div>   <!-- Progress Bar -->  <div class="progress" id="MKUID_progress">    <div class="progress-bar" id="MKUID_progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">      <span class="sr-only">0% Complete</span>    </div>  </div>  </form><!-- Upload Finished -->  <div class="js-upload-finished" id="MKUID_js-upload-finished" style="display: none;">    <h3>Processed files</h3>    <div class="list-group" id="MKUID_list_group">     </div>  </div></div> </div>',
    "UPLDND_OLD"	: '<div ><div class="panel-body" id="MKUID">   <!-- Standar Form -->  <!-- <h4>Select files from your computer</h4> --> <form action="" method="post" enctype="multipart/form-data" id="MKUID_js-upload-form" class="js-upload-form">   <!-- <div class="form-inline">      <div class="form-group">   -->     <input type="file" name="files[]" id="js-upload-files" class="hidden" multiple>    <!--  </div>      <button type="submit" class="btn btn-sm btn-primary hidden" id="js-upload-submit">Upload files</button>    </div>  -->   <!-- Drop Zone -->  <!-- <h4>Or drag and drop files below</h4> --> <div class="upload-drop-zone" id="MKUID_drop-zone">    Just drag and drop files here  </div>   <!-- Progress Bar -->  <div class="progress" id="MKUID_progress">    <div class="progress-bar" id="MKUID_progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">      <span class="sr-only">0% Complete</span>    </div>  </div>  </form><!-- Upload Finished -->  <div class="js-upload-finished" id="MKUID_js-upload-finished" style="display: none;">    <h3>Processed files</h3>    <div class="list-group" id="MKUID_list_group">     </div>  </div></div> </div>',
    "UPLDND"	: '<div> <div class="panel-body" id="MKUID"> <!-- Standar Form --> <form action="" method="post" enctype="multipart/form-data" id="MKUID_js-upload-form" class="js-upload-form">  <input type="file" name="files[]" id="js-upload-files" class="hidden" multiple="">  <!-- Drop Zone --> <div class="upload-drop-zone" id="MKUID_drop-zone"><span class="text-msg">Just drag and drop files here</span></div> <!-- Progress Bar --> <div class="progress" id="MKUID_progress"> <div class="progress-bar" id="MKUID_progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"> <span class="sr-only">0% Complete</span> </div> </div> </form> <!-- Upload Finished --> <div class="js-upload-finished" id="MKUID_js-upload-finished"> <ul class="list-group" id="MKUID_list_group">  </ul> </div> </div> </div>',
    "UPLOAD"    : '<div class="box-photo-add-vuoto" id="MKUID"> <div class="upload-drop-zone" id="MKUID_drop-zone" > <img id="MKUID_img_src" class="thumbnail img-responsive" style="height: 177px; width: 200px;" /> <input type="file" name="files[]" id="MKUID_upl" style="display:none;" /> <input type="text" name="upl_img" id="MKUID_text-upload"	class="form-control" value="" style="display:none;"/> </div> <img src="images/add-image.png" width="32" class="img-abs-center" alt=""/> </div> '
}

